[book]
authors = ["deep2code"]
language = "zh"
multilingual = false
src = "src"
title = "技术博客"
description = "记录技术积累"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false

[preprocessor.graphviz.options]
format = "svg"

[preprocessor.plantuml]
command = "mdbook-plantuml"

[preprocessor.toc]
command = "mdbook-toc"
max-level = 3

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
