name: Deploy mdBook
on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - "book.toml"
      - ".github/workflows/deploy-mdbook.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 确保获取完整历史，可能对某些插件有帮助

      - name: 安装系统依赖(graphviz)
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: 官方Rust工具链
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: 缓存Rust依赖,加速构建
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ runner.os }}-cargo

      - name: 安装mdBook和插件
        run: |
          # 安装指定版本的mdBook
          cargo install mdbook
          # 安装插件
          cargo install mdbook-mermaid
          cargo install mdbook-graphviz
          cargo install mdbook-toc
          cargo install mdbook-reading-time

      - name: 构建静态网站
        run: mdbook build
        continue-on-error: false # 构建失败则终止

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

      - name: 部署到GitHub Pages
        uses: actions/deploy-pages@v3
